### ISSUE TITLE
Panic on missing dotnet framework

### ISSUE THREAD

**Issue by douweschulte** [mobiusklein/mzdata#8]
When trying to open a raw ms file using the general [`open_path`](https://docs.rs/mzdata/0.28.1/mzdata/io/trait.MZFileReader.html#method.open_path) function it panics internally if you open a raw file without having the correct dotnet framework. I would like to give users of the annotator a nice error message if the dotnet is missing and point them to how to install it but with the current function there is no easy way to do this. Do you have any thoughts on how to return a good error from this function?

**Comment by mobiusklein** [comment]
I can see the issue. `dotnetrawfilereader-sys` pretty aggressively unwraps things. If I allow it to propagate all the way through `RawFileReader::new`, it will surface in `mzdata`.

Since `mzdata` requires an I/O error, I'll store the relevant error in the `io::Error`'s `source` under an `io::ErrorKind::Other`. It won't be the most convenient to check programmatically, but it will be in the error message and you will be able to reach the original error.

**Comment by douweschulte** [comment]
That sounds perfect! I will have to handle that `io::Error` anyways to show a nice error to the user so fully dissecting that error sound good to me.

**Comment by mobiusklein** [comment]
Did the recent changes resolve this issue for you?

**Comment by douweschulte** [comment]
Yes I made some code based on the exact message, this seems to work most of the time. Thanks for addressing this!
